trigger:  
- main  
  
pool:  
  vmImage: 'ubuntu-latest'  
  
steps:  
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/DEV'
    environmentServiceNameAzureRM: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    backendAzureRmContainerName: 'terraformstate'  
    backendAzureRmKey: 'terraform.tfstate'  
    # backendAzureRmResourceGroupName: 
    # backendAzureRmStorageAccountName: 
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/DEV'  
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'