trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal -u $(clientId) -p $(clientSecret) --tenant $(tenantId)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform init'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform validate'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform plan'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform apply'