# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/DEV'
    backendServiceArm: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/DEV'
    environmentServiceNameAzureRM: 'Sottoscrizione Penco(3d600cb7-0544-4631-9116-27e1e1f3343f)'